test 41

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -28,12 +28,24 @@ jobs:
       - run:
           name: "Run tests and create coverage html report"
           command: |
-            npm run test:coverage
+            npm run test:coverage-badges
       - run:
           name: "Update PR with the coverage report"
           command: |
             # Get the PR number
-            PR_NUMBER="${CIRCLE_PULL_REQUEST##*/}"
+            #PR_NUMBER="${CIRCLE_PULL_REQUEST##*/}"
+
+            #GITHUB_PULL_REQUEST_EVENT_BODY=$(jq --raw-output .pull_request.body "$GITHUB_EVENT_PATH")
+            #PR_DESCRIPTION_PATTERN='^((.|\n)*)\*\*Reason for low FE coverage\*\*:((.|\n)*)$'
+
+            #if [[ ! $GITHUB_PULL_REQUEST_EVENT_BODY =~ $PR_DESCRIPTION_PATTERN ]]; then
+            #  echo "The PR description doesn't contain the required string '**Reason for low FE coverage**:'"
+            #  echo "Please check how to fix it in https://hyperscience.atlassian.net/wiki/spaces/EN/pages/2950725665/Github+Pull+Requests+-+How-to+Best+Practices#Include-tests-in-pull-requests"
+            #  exit 1
+            #fi
+
+            comment_body="![Branches](https://circleci.com/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/artifacts/${CIRCLE_NODE_INDEX}/coverage/badge-branches.svg) ![Functions](https://circleci.com/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/artifacts/${CIRCLE_NODE_INDEX}/coverage/badge-functions.svg) ![Lines](https://circleci.com/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/artifacts/${CIRCLE_NODE_INDEX}/coverage/badge-lines.svg) ![Statements](https://circleci.com/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/artifacts/${CIRCLE_NODE_INDEX}/coverage/badge-statements.svg)\n\nCoverage report: [Coverage Report](https://circleci.com/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM/artifacts/${CIRCLE_NODE_INDEX}/coverage/lcov-report/index.html)"
+
 
             # Store the api endpoint for the PR
             ISSUES_API_ENDPOINT=https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/issues
@@ -48,7 +60,7 @@ jobs:
             HIDDEN_COMMENT_START="<!-- Jest Coverage Comment:Begin -->"
             HIDDEN_COMMENT_END="<!-- Jest Coverage Comment:End -->"
             HIDDEN_COMMENT="$HIDDEN_COMMENT_START $HIDDEN_COMMENT_END"
-            NEW_COMMENT="<details><summary>Code coverage report</summary>Code coverage report is available <a href=\"$ARTIFACT_URL\">here</a>.</details>"
+            NEW_COMMENT="$comment_body<br><details><summary>Code coverage report</summary>Code coverage report is available <a href=\"$ARTIFACT_URL\">here</a>.</details>"
             echo "New comment: $HIDDEN_COMMENT $NEW_COMMENT"
 
             # Create the JSON body for the comment
