quotes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -60,18 +60,19 @@ jobs:
             if [ "$COMMENT_ID" != "" ]; then
               echo "Existing coverage comment found. Updating it..."
               API_URL="$PR_API_ENDPOINT/comments/$COMMENT_ID"
-              curl_command=$(curl -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"body\":\"$HIDDEN_COMMENT $NEW_COMMENT\"}" $API_URL)
+              curl_command=$(curl -X PATCH -H 'Authorization: Bearer $GITHUB_TOKEN' -d '{\"body\":\"$HIDDEN_COMMENT $NEW_COMMENT\"}' $API_URL)
               response_code=$($curl_command -o /dev/null -w '%{http_code}')
             else
+              echo "Creating a new coverage comment..."
               API_URL="$PR_API_ENDPOINT/comments"
-              curl_command=$(curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"body\":\"$NEW_COMMENT\"}" $API_URL)
+              curl_command="$(curl -X POST -H 'Authorization: Bearer $GITHUB_TOKEN' -d '{\"body\":\"$NEW_COMMENT\"}' $API_URL)"
               response_code=$($curl_command -o /dev/null -w '%{http_code}')
             fi
 
             echo "response_code: $response_code"
             if [[ "$response_code" =~ ^2[0-9][0-9]$ ]]; then
               echo "Curl request failed with HTTP status code $response_code"
-              exit 1  # This will fail the CircleCI job
+              exit 1  # Fail the CircleCI job
             else
               echo "Curl request was successful with HTTP status code $response_code"
             fi
