now

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -62,10 +62,17 @@ jobs:
             # If the comment was found, update it; otherwise, create a new one
             if [ "$COMMENT_ID" != "" ]; then
               API_URL="$PR_API_ENDPOINT/comments/$COMMENT_ID"
-              curl -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"body\":\"$HIDDEN_COMMENT $NEW_COMMENT\"}" $API_URL
+              response_code=$(curl -X PATCH -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"body\":\"$HIDDEN_COMMENT $NEW_COMMENT\"}" $API_URL)
             else
               API_URL="$PR_API_ENDPOINT/comments"
-              curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"body\":\"{{ NEW_COMMENT }}\"}" $API_URL
+              response_code=$(curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" -d "{\"body\":\"{{ NEW_COMMENT }}\"}" $API_URL)
+            fi
+
+            if [[ "$response_code" =~ ^2[0-9][0-9]$ ]]; then
+              echo "Curl request failed with HTTP status code $response_code"
+              exit 1  # This will fail the CircleCI job
+            else
+              echo "Curl request was successful with HTTP status code $response_code"
             fi
           when: on_success
       - store_artifacts:
